"""Shared, scoped styling for scientific plots generated by the project."""

from __future__ import annotations

from functools import wraps

import matplotlib
from cycler import cycler

BLUES_6 = ("#EFF3FF", "#C6DBEF", "#9ECAE1", "#6BAED6", "#3182BD", "#08519C")
EARTH_5 = ("#FCFAE1", "#EDE2B5", "#CABD91", "#6F6357", "#584A47")
ACCENT_RED = "#9F2B2C"

# Ordered for distinct categorical marks on a light background, not as a continuous scale.
CATEGORICAL_8 = (
    "#08519C", ACCENT_RED, "#6F6357", "#3182BD",
    "#584A47", "#6BAED6", "#CABD91", "#9ECAE1",
)
FOLD_COLORS = ("#08519C", "#3182BD", "#6BAED6", "#6F6357", "#584A47", "#9ECAE1")
LINE_STYLES = ("-", "--", ":", "-.")
MARKERS = ("o", "s", "^", "D", "P", "X")

EXPORT_DPI = 300
EMBED_DPI = 160

PLOT_RC = {
    "axes.axisbelow": True,
    "axes.edgecolor": "#CABD91",
    "axes.facecolor": "white",
    "axes.grid": False,
    "axes.labelcolor": "#584A47",
    "axes.prop_cycle": cycler(color=CATEGORICAL_8),
    "axes.spines.right": False,
    "axes.spines.top": False,
    "axes.titlecolor": "#584A47",
    "axes.titleweight": "semibold",
    "figure.facecolor": "white",
    "font.family": "sans-serif",
    "grid.alpha": 0.35,
    "grid.color": "#CABD91",
    "grid.linewidth": 0.7,
    "legend.frameon": False,
    "savefig.facecolor": "white",
    "text.color": "#584A47",
    "xtick.color": "#6F6357",
    "ytick.color": "#6F6357",
}

METRIC_COLORS = {
    "loss": ACCENT_RED,
    "dice": "#08519C",
    "iou": "#3182BD",
    "balanced_accuracy": "#08519C",
    "macro_f1": "#3182BD",
    "accuracy": "#6F6357",
    "auc": "#08519C",
    "auc_ovr_macro": "#08519C",
}


def with_plot_style(function):
    """Run one plot builder in an rc context without mutating global Matplotlib state."""
    @wraps(function)
    def wrapped(*args, **kwargs):
        with matplotlib.rc_context(PLOT_RC):
            return function(*args, **kwargs)
    return wrapped


def categorical_color(index):
    return CATEGORICAL_8[int(index) % len(CATEGORICAL_8)]


def fold_style(index):
    index = int(index)
    return {
        "color": FOLD_COLORS[index % len(FOLD_COLORS)],
        "linestyle": LINE_STYLES[index % len(LINE_STYLES)],
        "marker": MARKERS[index % len(MARKERS)],
    }


def metric_color(metric_name, fallback_index=0):
    name = str(metric_name).lower()
    if name in METRIC_COLORS:
        return METRIC_COLORS[name]
    if "loss" in name:
        return ACCENT_RED
    if "auc" in name:
        return METRIC_COLORS["auc"]
    return categorical_color(fallback_index)


def setup_color(label, fallback_index=0):
    """Keep experimental setup colors stable across reports and plot orderings."""
    name = str(label).lower().replace("_", "-")
    if "local" in name or "standalone" in name:
        return "#584A47"
    if "central" in name:
        return ACCENT_RED
    if "federat" in name or "fedper" in name:
        return "#08519C"
    return categorical_color(fallback_index)


def split_style(split, phase="", fallback_index=0):
    """Differentiate training/evaluation traces without relying on color alone."""
    split = str(split).lower()
    phase = str(phase).lower()
    if split in {"val", "validation"}:
        return {"linestyle": "-", "marker": "o"}
    if split == "test":
        return {"linestyle": ":", "marker": "^"}
    if "step" in phase:
        return {"linestyle": "--", "marker": None}
    if split == "train":
        return {"linestyle": "--", "marker": "s"}
    return {
        "linestyle": LINE_STYLES[int(fallback_index) % len(LINE_STYLES)],
        "marker": MARKERS[int(fallback_index) % len(MARKERS)],
    }


def style_axis(axis, *, grid_axis="y"):
    axis.set_axisbelow(True)
    axis.grid(True, axis=grid_axis, color="#CABD91", alpha=0.35, linewidth=0.7)
    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)
    axis.spines["left"].set_color("#CABD91")
    axis.spines["bottom"].set_color("#CABD91")
